backend:
  name: github
  repo: maixuanhoa/mydaught # Đúng tên repo của bạn
  branch: main # Nhánh bạn đang dùng

media_folder: "assets/images" # Nơi lưu ảnh bài viết
public_folder: "/assets/images"

collections:
  - name: "blog"
    label: "Bài viết Blog"
    folder: "_posts" # Bài viết sẽ tự lưu vào thư mục này
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Tiêu đề", name: "title", widget: "string" }
      - { label: "Ngày đăng", name: "date", widget: "datetime" }
      - { label: "Ảnh bìa", name: "thumbnail", widget: "image" }
      - { label: "Nội dung bài viết", name: "body", widget: "markdown" }
